import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Particles } from "@/components/ui/shadcn-io/particles";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} font-sans antialiased
        bg-gradient-to-br
        from-[oklch(0.1441_0.0604_287.71)] via-[oklch(0.144_0.1631_283.1)] to-[oklch(0.1441_0.0604_287.71)]
        `}
      >
        <Particles
      className="fixed inset-0 -z-10"
      quantity={120}
      ease={10}
      staticity={100}
      color="#F29EFA"
      size={2.0}
      vx={0.2}
      vy={0.2}
      refresh
    />
        {children}
      </body>
    </html>
  );
}
